server:
  port: 8222
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8890
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: http://localhost:8891
          predicates:
            - Path=/api/v1/user/**
        - id: hotel-service
          uri: http://localhost:8892
          predicates:
            - Path=/api/v1/hotel/**
        - id: booking-service
          uri: http://localhost:8893
          predicates:
            - Path=/api/v1/booking/**
        - id: notification-service
          uri: http://localhost:8894
          predicates:
            - Path=/api/v1/notifications/**
        - id: search-service
          uri: http://localhost:8895
          predicates:
            - Path=/api/v1/search/**
#management:
#  tracing:
#    sampling:
#      probability: 1.0